### PR TITLE
Add new dub release 0.9.24.

### PR DESCRIPTION
**Pull request by redstar**

### CODE REVIEW

**Comment by mleise** [comment]
Little nag: New ebuilds should generally be ~KEYWORD unless it is an urgent security hotfix. (https://marc.info/?l=gentoo-dev&m=118229259232550)
Looks good to merge otherwise.

**Comment by redstar** [comment]
Thanks for the hint. It's fixed now.

**Comment by mleise** [comment]
I just tried it. Could you change the minimal required D version to 2.066 in the ebuild? Earlier versions complain about `source/dub/internal/vibecompat/data/utils.d(153): Error: variable t used before set`. Sorry I skipped the question if you tested it with the lowest of supported versions, hoping that it would still compile with 2.064.

**Comment by mleise** [comment]
I messed up the commit history again, but this is merged now. Thanks.
